// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallAPI'](arg1, arg2, arg3);
}

export function ChatStream(arg1, arg2) {
  return window['go']['main']['App']['ChatStream'](arg1, arg2);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetIPCStatus() {
  return window['go']['main']['App']['GetIPCStatus']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideBubble() {
  return window['go']['main']['App']['HideBubble']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PollDeviceLogin(arg1) {
  return window['go']['main']['App']['PollDeviceLogin'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function ShowBubble(arg1) {
  return window['go']['main']['App']['ShowBubble'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartDeviceLogin() {
  return window['go']['main']['App']['StartDeviceLogin']();
}
