// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CallAPI(arg1:string,arg2:string,arg3:string):Promise<Array<number>>;

export function CancelChat(arg1:string):Promise<void>;

export function ChatStream(arg1:string):Promise<void>;

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetIPCStatus():Promise<Record<string, any>>;

export function GetServiceStatus():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function HideBubble():Promise<void>;

export function HideWindow():Promise<void>;

export function Logout():Promise<void>;

export function PollDeviceLogin(arg1:string):Promise<main.AuthResult>;

export function Quit():Promise<void>;

export function RestartService():Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function ShowBubble(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartDeviceLogin():Promise<main.DeviceCodeResponse>;
