// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallAPI(arg1, arg2, arg3) {
  return window['go']['backend']['APIClient']['CallAPI'](arg1, arg2, arg3);
}

export function CallAPITyped(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['APIClient']['CallAPITyped'](arg1, arg2, arg3, arg4);
}

export function CallAPIWithBody(arg1, arg2, arg3) {
  return window['go']['backend']['APIClient']['CallAPIWithBody'](arg1, arg2, arg3);
}

export function Delete(arg1) {
  return window['go']['backend']['APIClient']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['backend']['APIClient']['Get'](arg1);
}

export function GetBaseURL() {
  return window['go']['backend']['APIClient']['GetBaseURL']();
}

export function Patch(arg1, arg2) {
  return window['go']['backend']['APIClient']['Patch'](arg1, arg2);
}

export function Post(arg1, arg2) {
  return window['go']['backend']['APIClient']['Post'](arg1, arg2);
}

export function Put(arg1, arg2) {
  return window['go']['backend']['APIClient']['Put'](arg1, arg2);
}

export function SetTimeout(arg1) {
  return window['go']['backend']['APIClient']['SetTimeout'](arg1);
}
