// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';

export function CallAPI(arg1:string,arg2:string,arg3:string):Promise<Array<number>>;

export function CallAPITyped(arg1:string,arg2:string,arg3:any,arg4:any):Promise<void>;

export function CallAPIWithBody(arg1:string,arg2:string,arg3:any):Promise<Array<number>>;

export function Delete(arg1:string):Promise<Array<number>>;

export function Get(arg1:string):Promise<Array<number>>;

export function GetBaseURL():Promise<string>;

export function Patch(arg1:string,arg2:any):Promise<Array<number>>;

export function Post(arg1:string,arg2:any):Promise<Array<number>>;

export function Put(arg1:string,arg2:any):Promise<Array<number>>;

export function SetTimeout(arg1:time.Duration):Promise<void>;
